[PDP_History]:
LOAD
 DISPLAY_NAME
,EDITED_FIELD
,ADMINISTRATOR_FULL_NAME	
,TEAM_FILTER
,EDITED_AT
,SEGMENT_NAME
,BRAND_NAME
,FIRST_LEVEL_PRODUCT_TYPE
,SECOND_LEVEL_PRODUCT_TYPE
,THIRD_LEVEL_PRODUCT_TYPE
,FOURTH_LEVEL_PRODUCT_TYPE
,FIFTH_LEVEL_PRODUCT_TYPE
,SIXTH_LEVEL_PRODUCT_TYPE
,FISCAL_YEAR
,FISCAL_PERIOD
,FISCAL_QUARTER
,FISCAL_WEEK
,FISCAL_YEAR_PERIOD
,FISCAL_YEAR_WEEK
;
SQL
WITH PRODUCTS AS (
SELECT
  ANALYTICS.PUBLIC.PRODUCTS.ID,
  ANALYTICS.PUBLIC.PRODUCTS.APPAREL_TYPE,
  ANALYTICS.PUBLIC.PRODUCTS.SEGMENT_NAME,
  ANALYTICS.PUBLIC.PRODUCTS.DISPLAY_NAME,
  ANALYTICS.PUBLIC.PRODUCTS.BRAND_ID

FROM ANALYTICS.PUBLIC.PRODUCTS
LEFT JOIN RAW_ECOM.PUBLIC.PRODUCTS ADMIN
   ON ADMIN.ID = PRODUCTS.ID
),

BASE AS (SELECT 
PRODUCTS.DISPLAY_NAME,
INITCAP (RAW_ECOM.PUBLIC.MODEL_AUDITS.FIELD) as EDITED_FIELD,
ANALYTICS.PUBLIC.ADMINISTRATORS.ADMINISTRATOR_FULL_NAME,
RAW_ECOM.PUBLIC.MODEL_AUDITS.CREATED_AT::DATE AS EDITED_AT,
PRODUCTS.SEGMENT_NAME,
ANALYTICS.PUBLIC.BRANDS.BRAND_NAME,
ANALYTICS.PUBLIC.PRODUCT_TYPES.FIRST_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.PRODUCT_TYPES.SECOND_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.PRODUCT_TYPES.THIRD_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.PRODUCT_TYPES.FOURTH_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.PRODUCT_TYPES.FIFTH_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.PRODUCT_TYPES.SIXTH_LEVEL_PRODUCT_TYPE,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_YEAR,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_QUARTER,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_PERIOD,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_WEEK,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_YEAR_PERIOD,
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.FISCAL_YEAR_WEEK

FROM 
RAW_ECOM.PUBLIC.MODEL_AUDITS
         
LEFT JOIN
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN
ON
ANALYTICS.PUBLIC.FISCAL_CALENDARS_DRIVETRAIN.DATE = RAW_ECOM.PUBLIC.MODEL_AUDITS.CREATED_AT::DATE
                 
LEFT JOIN 
ANALYTICS.PUBLIC.ADMINISTRATORS
ON 
RAW_ECOM.PUBLIC.MODEL_AUDITS.USER_ID = ANALYTICS.PUBLIC.ADMINISTRATORS.ADMINISTRATOR_ID

LEFT JOIN
PRODUCTS
ON
RAW_ECOM.PUBLIC.MODEL_AUDITS.MODEL_ID = PRODUCTS.ID

LEFT JOIN 
ANALYTICS.PUBLIC.BRANDS
ON 
PRODUCTS.BRAND_ID = ANALYTICS.PUBLIC.BRANDS.BRAND_ID

LEFT JOIN 
ANALYTICS.PUBLIC.PRODUCT_TYPES
ON 
PRODUCTS.APPAREL_TYPE = ANALYTICS.PUBLIC.PRODUCT_TYPES.PRODUCT_TYPE_ID

WHERE PRODUCTS.DISPLAY_NAME IS NOT NULL
AND FISCAL_YEAR >=2020     

)

SELECT *
,CASE
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Alan%Hilker') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Corey%Ruiz') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Nick%Fiorilli') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('George%Armenante') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Hao%Dong') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Jon%Santos') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Justin%Regan') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Kyle%Jones') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Mark%Ortner') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Meg%Walters') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Ryan%Williams') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Rob%Kirkpatrick') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Tom%Mele') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Derek%Cabrera') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Sarah%Giampietro') THEN 'Catalog'
WHEN ADMINISTRATOR_FULL_NAME LIKE ('Zach%Smith') THEN 'Catalog'
ELSE 'Other'
END AS TEAM_FILTER
FROM BASE
WHERE EDITED_FIELD NOT IN ('Long_Description_Values','Teaser_Values','Teaser')




